# Generated by Django 4.0.3 on 2022-04-13 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_country_timezones_city_timezones_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timezones',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
